name: frontend_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  sign_in_button: ^3.2.0
  google_sign_in_web: ^0.12.4+3
  flutter_secure_storage: ^5.0.2
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
